'use strict';

const PATTERNS = [
  {
    id: 'EVASION-011',
    type: 'OS_COMMAND_EXECUTION',
    regex: /child_process\.(exec|execSync|spawn|fork|execFile)/g,
    severity: 'HIGH',
    risk: 8,
    category: 'execution',
    description: 'Direct child_process execution method detected',
  },
  {
    id: 'EVASION-011b',
    type: 'OS_COMMAND_EXECUTION',
    regex: /require\s*\(\s*['"]child_process['"]\s*\)\s*\.\s*(exec|execSync|spawn|fork)\s*\(/g,
    severity: 'HIGH',
    risk: 8,
    category: 'execution',
    description: 'Chained require child_process execution detected',
  },
  {
    id: 'EVASION-011c',
    type: 'OS_COMMAND_EXECUTION',
    regex: /require\s*\(\s*['"]child_process['"]\s*\)\s*\[\s*['"]/g,
    severity: 'HIGH',
    risk: 9,
    category: 'execution',
    description: 'Bracket access to child_process module detected',
  },
  {
    id: 'EVASION-012',
    type: 'SHELL_PIVOT',
    regex: /(curl|wget)\s+.+\s*[|;]\s*(bash|sh|powershell)/gi,
    severity: 'CRITICAL',
    risk: 10,
    category: 'execution',
    description: 'Remote download piped to shell interpreter',
  },
  {
    id: 'EVASION-013',
    // NOTE: EVASION-013 moved to heuristics.js for context gating.
    // Stub preserved at LOW severity as fallback.
    type: 'UNSAFE_EVAL',
    regex: /eval\s*\(/g,
    severity: 'LOW',
    risk: 2,
    category: 'execution',
    description: 'Direct eval() call for arbitrary code execution',
  },
  {
    id: 'EVASION-014',
    type: 'FUNCTION_CONSTRUCTOR',
    regex: /new\s+Function\s*\(/g,
    severity: 'HIGH',
    risk: 8,
    category: 'execution',
    description: 'Function constructor as eval alternative',
  },
  {
    id: 'EVASION-014b',
    type: 'FUNCTION_CONSTRUCTOR',
    regex: /Function\s*\(\s*['"]/g,
    severity: 'HIGH',
    risk: 8,
    category: 'execution',
    description: 'Function() call with string argument',
  },
  {
    id: 'EVASION-021',
    type: 'OUTBOUND_NETWORK',
    regex: /(fetch|axios|got|superagent|request)\s*\(/g,
    severity: 'HIGH',
    risk: 7,
    category: 'execution',
    description: 'HTTP client library invocation for potential exfiltration',
  },
  {
    id: 'EVASION-021b',
    type: 'OUTBOUND_NETWORK',
    regex: /require\s*\(\s*['"]https?['"]\s*\)\s*\.\s*(get|request)/g,
    severity: 'HIGH',
    risk: 7,
    category: 'execution',
    description: 'Native http/https module request',
  },
  {
    id: 'EVASION-022',
    type: 'OUTBOUND_NETWORK',
    regex: /new\s+WebSocket\s*\(/g,
    severity: 'HIGH',
    risk: 7,
    category: 'execution',
    description: 'WebSocket connection for real-time data exfiltration',
  },
  {
    id: 'EVASION-023',
    // NOTE: EVASION-023 moved to heuristics.js for context gating.
    // The heuristic version applies LOW severity when the value is
    // an encoded/blob string, in test context, or has no decode/exec/
    // network/filesystem context. Keep this stub as a fallback with
    // reduced default severity.
    type: 'HARDCODED_SECRET',
    regex: /(?:api[_-]?key|secret|password|token)\s*[:=]\s*['"][A-Za-z0-9_\-]{16,}['"]/gi,
    severity: 'LOW',
    risk: 2,
    category: 'supply_chain',
    description: 'Hardcoded credential of significant length detected',
  },
  {
    id: 'EVASION-024',
    // NOTE: EVASION-024 moved to heuristics.js for context gating.
    // The heuristic version applies LOW severity when no exfiltration
    // or execution context is present. Keep this stub as a fallback
    // with reduced default severity.
    type: 'HARDCODED_SECRET',
    regex: /process\.env\.(?:GITHUB_TOKEN|AWS_|NPM_TOKEN|SLACK_)/g,
    severity: 'LOW',
    risk: 2,
    category: 'supply_chain',
    description: 'Reference to known CI/CD secret environment variable',
  },
  {
    id: 'EVASION-025',
    type: 'MALICIOUS_LIFECYCLE_SCRIPT',
    regex: /"(?:post|pre)install"\s*:\s*"/g,
    severity: 'HIGH',
    risk: 8,
    category: 'supply_chain',
    description: 'Postinstall/preinstall lifecycle script in package.json',
  },
  {
    id: 'EVASION-026',
    type: 'SUSPICIOUS_REGISTRY',
    regex: /registry\s*[=:]\s*["']?https?:\/\/(?!registry\.npmjs\.org)/gi,
    severity: 'HIGH',
    risk: 8,
    category: 'supply_chain',
    description: 'Non-standard npm registry URL (dependency confusion risk)',
  },
  {
    id: 'EVASION-027',
    type: 'PROTOTYPE_POLLUTION',
    regex: /__proto__|constructor\.prototype/gi,
    severity: 'HIGH',
    risk: 7,
    category: 'execution',
    description: 'Prototype pollution via __proto__ or constructor.prototype',
  },
  {
    id: 'EVASION-034',
    type: 'DOM_XSS',
    regex: /innerHTML\s*=/g,
    severity: 'HIGH',
    risk: 7,
    category: 'execution',
    description: 'innerHTML assignment (XSS vector in JS/TS)',
  },
  {
    id: 'EVASION-029',
    type: 'BASE64_ENCODE',
    regex: /btoa\s*\(|Buffer\.from\s*\(.*base64/gi,
    severity: 'MEDIUM',
    risk: 5,
    category: 'obfuscation',
    description: 'Base64 encoding operation detected',
  },
  {
    id: 'EVASION-030',
    type: 'BASE64_DECODE',
    regex: /atob\s*\(|\.toString\s*\(\s*['"](?:ascii|utf-?8|binary)['"]\s*\)/gi,
    severity: 'MEDIUM',
    risk: 5,
    category: 'obfuscation',
    description: 'Base64/encoding decode operation detected',
  },
  {
    id: 'EVASION-028',
    type: 'DYNAMIC_REQUIRE',
    regex: /require\s*\(\s*[^'"\s]/g,
    severity: 'MEDIUM',
    risk: 5,
    category: 'execution',
    description: 'Dynamic require() with non-string argument',
  },
  {
    id: 'EVASION-015',
    type: 'VM_ESCAPE',
    regex: /require\s*\(\s*['"]vm['"]\s*\)/g,
    severity: 'HIGH',
    risk: 8,
    category: 'execution',
    description: 'VM module import (sandbox escape vector)',
  },
  {
    id: 'EVASION-035',
    type: 'WORKER_THREAD',
    regex: /require\s*\(\s*['"]worker_threads['"]\s*\)/g,
    severity: 'MEDIUM',
    risk: 6,
    category: 'execution',
    description: 'Worker threads module import',
  },
  {
    id: 'EVASION-016',
    type: 'MODULE_CONSTRUCTOR',
    regex: /require\s*\(\s*['"]module['"]\s*\)\s*\.\s*constructor/g,
    severity: 'HIGH',
    risk: 8,
    category: 'execution',
    description: 'Module constructor access for module system manipulation',
  },
  {
    id: 'EVASION-031',
    type: 'DELAYED_EXECUTION',
    regex: /setTimeout\s*\(\s*["'`]/g,
    severity: 'MEDIUM',
    risk: 5,
    category: 'execution',
    description: 'setTimeout with string argument (eval-like delayed execution)',
  },
  {
    id: 'EVASION-032',
    type: 'DELAYED_EXECUTION',
    regex: /setImmediate\s*\(\s*["'`]/g,
    severity: 'MEDIUM',
    risk: 5,
    category: 'execution',
    description: 'setImmediate with string argument (eval-like delayed execution)',
  },
  {
    id: 'EVASION-008',
    type: 'PROMPT_INJECTION',
    regex: /ignore\s+(?:all\s+)?previous\s+instructions/gi,
    severity: 'CRITICAL',
    risk: 10,
    category: 'prompt_attack',
    description: 'Ignore previous instructions detected — prompt injection attempt',
  },
  {
    id: 'EVASION-009',
    type: 'PROMPT_INJECTION',
    regex: /\[SYSTEM:?\s/g,
    severity: 'MEDIUM',
    risk: 5,
    category: 'prompt_attack',
    description: 'System prompt override marker detected',
  },
  {
    id: 'EVASION-009b',
    type: 'PROMPT_INJECTION',
    regex: /<!--\s*SYSTEM\s*:/gi,
    severity: 'HIGH',
    risk: 7,
    category: 'prompt_attack',
    description: 'HTML comment system prompt override detected',
  },
  {
    id: 'EVASION-009c',
    type: 'PROMPT_INJECTION',
    regex: /<!--\s*SYSTEM[^>]*(?:execute|exec|curl|wget|run|install|fetch|spawn).*-->/gi,
    severity: 'CRITICAL',
    risk: 10,
    category: 'prompt_attack',
    description: 'HTML comment system marker with execution command detected',
  },
  {
    id: 'EVASION-010',
    type: 'AGENT_TOOL_MISUSE',
    regex: /call_tool\s*\(/g,
    severity: 'HIGH',
    risk: 8,
    category: 'prompt_attack',
    description: 'Direct tool call invocation via call_tool()',
  },
  {
    id: 'EVASION-010b',
    type: 'AGENT_TOOL_MISUSE',
    regex: /"method"\s*:\s*"tools\/call"/g,
    severity: 'HIGH',
    risk: 8,
    category: 'prompt_attack',
    description: 'JSON-RPC tools/call method injection',
  },
  {
    id: 'EVASION-035',
    type: 'WORKER_THREAD_CREATION',
    regex: /require\s*\(\s*['"]worker_threads['"]\s*\)/g,
    severity: 'MEDIUM',
    risk: 5,
    category: 'module_import',
    description: 'worker_threads module required',
  },
  {
    id: 'EVASION-035b',
    type: 'WORKER_THREAD_CREATION',
    regex: /new\s+Worker\s*\(/g,
    severity: 'HIGH',
    risk: 7,
    category: 'sandbox_escape',
    description: 'Worker thread creation with dynamic code',
  },
  {
    id: 'EVASION-036',
    type: 'PROTOTYPE_POLLUTION',
    regex: /\.__proto__\s*=|\.prototype\s*\[|\.prototype\./g,
    severity: 'HIGH',
    risk: 8,
    category: 'obfuscation',
    description: 'Prototype pollution assignment detected',
  },
  {
    id: 'EVASION-036b',
    type: 'PROTOTYPE_POLLUTION',
    regex: /(?:\.__proto__\s*=|\.prototype\s*\[|\.prototype\.\w+\s*=)[^;]*;\s*(?:.*require\s*\(|.*exec|.*spawn|.*fork)/gs,
    severity: 'CRITICAL',
    risk: 10,
    category: 'execution',
    description: 'Prototype pollution leading to code execution',
  },
];

function scanPatterns(code) {
  const findings = [];
  for (const pattern of PATTERNS) {
    pattern.regex.lastIndex = 0;
    let match;
    while ((match = pattern.regex.exec(code)) !== null) {
      findings.push({
        id: pattern.id,
        type: pattern.type,
        severity: pattern.severity,
        risk: pattern.risk,
        category: pattern.category,
        description: pattern.description,
        match: match[0].substring(0, 120),
        source: 'PATTERN',
      });
    }
  }
  return findings;
}

module.exports = { PATTERNS, scanPatterns };
