import React, { useState } from 'react';
import { UploadCloud, FileJson, AlertCircle, RefreshCw, AlertTriangle, ArrowRight } from 'lucide-react';
import { PostureOverview } from './PostureOverview';
import { SemanticFindings } from './SemanticFindings';
import { ThreatDrillDown } from './ThreatDrillDown';
import { Parsers } from './SentinelReportSchema';
import { normalizeReport_v361, NormalizedReportModel, NormalizedFinding } from './SentinelNormalizer';

type ErrorUX = {
    title: string;
    reason: string[];
    action: string[];
};

export const JsonReplayScanner: React.FC = () => {
    const [snapshot, setSnapshot] = useState<NormalizedReportModel | null>(null);
    const [errorData, setErrorData] = useState<ErrorUX | null>(null);
    const [selectedThreat, setSelectedThreat] = useState<NormalizedFinding | null>(null);

    const fail = (title: string, reason: string | string[], action: string | string[]) => {
        setErrorData({
            title,
            reason: Array.isArray(reason) ? reason : [reason],
            action: Array.isArray(action) ? action : [action]
        });
        setSnapshot(null);
    };

    const handleFileUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
        const file = event.target.files?.[0];
        if (!file) return;

        // Limite estricto de 5MB
        if (file.size > 5 * 1024 * 1024) {
            fail(
                "Performance Guardrail Blocked File",
                "JSON Payload exceeds maximum allocation size (5MB).",
                "Reduce scan scope or use a paginated Sentinel export format."
            );
            return;
        }

        const reader = new FileReader();
        reader.onload = (e) => {
            try {
                let rawJson = JSON.parse(e.target?.result as string);
                
                // Anti-Fragility: Unwrap 'respondAgent' standard API container if present
                if (rawJson.data && rawJson.success !== undefined) {
                    rawJson = rawJson.data;
                }
                
                // 1. Versioning Gate
                if (!rawJson.version) {
                    fail("Invalid Sentinel Format", "Missing payload 'version' header.", ["Verify file source.", "Re-export report using Sentinel CLI v3.6.1+"]);
                    return;
                }

                const parser = Parsers[rawJson.version];
                if (!parser) {
                    fail("Unsupported Version", `The visual dashboard does not support offline reports generated by Sentinel v${rawJson.version}.`, `Upgrade your local UI client or roll back your CLI generator to version 3.6.1.`);
                    return;
                }

                // 2. Strict Zod Validation Base
                const parsed = parser.safeParse(rawJson);
                
                if (!parsed.success) {
                    const issues = parsed.error.issues.map((iss: any) => `[${iss.path.join('.')}] - ${iss.message}`);
                    fail("Schema Malformation Detected", issues, "The JSON structure was tampered with or is corrupted. Re-run scan logic fresh from CLI.");
                    return;
                }
                
                // 3. Normalization Interface
                let normalized: NormalizedReportModel;
                if (rawJson.version === "3.6.1") {
                    normalized = normalizeReport_v361(parsed.data);
                } else {
                    // Fallback para ts safety, aunque parser lo garantizó
                    normalized = normalizeReport_v361(parsed.data); 
                }
                
                setSnapshot(normalized);
                setErrorData(null);
                setSelectedThreat(null);
            } catch (err: any) {
                fail("Parse Exception", "Fatal structural syntax error in JSON String.", "Provide a valid JSON file without trailing commas or syntax mistakes.");
            }
        };
        reader.readAsText(file);
    };

    if (errorData && !snapshot) {
        return (
            <div className="flex flex-col items-center justify-center h-full p-8">
                <div className="max-w-xl w-full bg-black/40 border border-red-500/20 rounded-3xl p-10 relative overflow-hidden text-left">
                    <div className="w-16 h-16 rounded-3xl bg-red-500/10 flex items-center justify-center mb-8 border border-red-500/20">
                        <AlertTriangle className="w-8 h-8 text-red-500" />
                    </div>
                    
                    <h2 className="text-2xl font-black text-white mb-8 border-b border-white/10 pb-4">{errorData.title}</h2>
                    
                    <div className="mb-8">
                        <p className="text-[10px] text-zinc-500 uppercase tracking-widest font-black mb-3">Reason:</p>
                        <ul className="space-y-2">
                            {errorData.reason.map((r, i) => (
                                <li key={i} className="text-sm font-mono text-zinc-300 flex items-start gap-3 bg-red-500/5 border border-red-500/10 p-3 rounded-xl border-l-2 border-l-red-500">
                                   {r}
                                </li>
                            ))}
                        </ul>
                    </div>
                    
                    <div className="mb-10">
                        <p className="text-[10px] text-zinc-500 uppercase tracking-widest font-black mb-3">Required Action:</p>
                        <ul className="space-y-2">
                            {errorData.action.map((a, i) => (
                                <li key={i} className="text-sm font-bold text-blue-300 flex items-center gap-3">
                                   <div className="w-5 h-5 rounded-full bg-blue-500/20 flex items-center justify-center">
                                       <ArrowRight className="w-3 h-3 text-blue-400" />
                                   </div>
                                   {a}
                                </li>
                            ))}
                        </ul>
                    </div>
                    
                    <div className="flex justify-start">
                        <button 
                            onClick={() => { setErrorData(null); setSnapshot(null); }}
                            className="px-6 py-2.5 bg-white/5 hover:bg-white/10 border border-white/10 rounded-xl text-xs font-bold text-white transition-all shadow-xl shadow-black/20"
                        >
                            Back to Scanner
                        </button>
                    </div>
                </div>
            </div>
        );
    }

    if (!snapshot) {
        return (
            <div className="flex flex-col items-center justify-center h-full p-8">
                <div className="max-w-md w-full bg-black/40 border border-white/10 rounded-3xl p-10 text-center relative overflow-hidden">
                    <div className="absolute top-0 right-0 w-64 h-64 bg-blue-500/10 blur-[80px] -z-10" />
                    
                    <div className="w-20 h-20 mx-auto rounded-3xl bg-blue-500/10 flex items-center justify-center mb-6 border border-blue-500/20">
                        <FileJson className="w-10 h-10 text-blue-400" />
                    </div>
                    
                    <h2 className="text-2xl font-black text-white mb-3">Replay Scanner</h2>
                    <p className="text-sm text-zinc-400 mb-8 leading-relaxed">
                        Upload a raw <code className="bg-white/5 text-blue-300 px-1.5 py-0.5 rounded">.json</code> snapshot generated by the Sentinel CLI to visualize the execution context safely.
                    </p>
                    
                    <label className="relative flex flex-col items-center justify-center w-full min-h-[140px] px-4 py-6 border-2 border-dashed border-white/20 rounded-2xl cursor-pointer hover:bg-white/5 hover:border-blue-500/50 transition-all group overflow-hidden">
                        <UploadCloud className="w-8 h-8 text-zinc-500 group-hover:text-blue-400 transition-colors mb-3 relative z-10" />
                        <span className="text-sm font-bold text-zinc-300 group-hover:text-blue-300 relative z-10">Drag & Drop Scan JSON</span>
                        <span className="text-xs text-zinc-500 mt-1 relative z-10">Max 5MB • Sentinel v3.6.1+</span>
                        <input type="file" accept=".json" className="hidden" onChange={handleFileUpload} />
                    </label>
                </div>
            </div>
        );
    }

    if (selectedThreat) {
         return (
            <div className="h-full flex flex-col">
                <div className="mb-6">
                    <button 
                        onClick={() => setSelectedThreat(null)}
                        className="text-sm text-zinc-400 hover:text-white flex items-center gap-2 mb-2 transition-colors"
                    >
                        ← Back to Overview
                    </button>
                    <h2 className="text-2xl font-black text-white truncate break-all">
                        {selectedThreat.targetName}
                    </h2>
                    <p className="text-sm text-zinc-500">Forensic Trace & Explainability Deck</p>
                </div>
                
                <div className="flex-1 overflow-y-auto">
                    <ThreatDrillDown threat={selectedThreat} context={snapshot.meta} />
                </div>
            </div>
         );
    }

    return (
        <div className="h-full flex flex-col px-1 pb-10 overflow-y-auto overflow-x-hidden space-y-8">
            <div className="flex items-center justify-between mt-2">
                <div>
                    <h2 className="text-2xl font-black text-white">Visual Reports</h2>
                    <p className="text-sm text-zinc-500 font-mono tracking-tight flex items-center gap-2">
                        Sentinel Offline Snapshot <span className="bg-white/10 px-1.5 py-0.5 rounded text-[9px]">Engine v{snapshot.meta.version}</span>
                        <span className="bg-blue-500/10 text-blue-400 border border-blue-500/20 px-1.5 py-0.5 rounded text-[9px]">Rulepack {snapshot.meta.rulepack}</span>
                    </p>
                </div>
                <button 
                    onClick={() => { setSnapshot(null); setErrorData(null); }}
                    className="flex items-center gap-2 px-4 py-2 bg-white/5 hover:bg-white/10 border border-white/10 rounded-xl text-xs font-bold text-white transition-all shadow-xl shadow-black/20"
                >
                    <RefreshCw className="w-3.5 h-3.5" />
                    Load New Scan
                </button>
            </div>
            
            <PostureOverview data={snapshot} />
            
            <SemanticFindings 
                alerts={snapshot.findings} 
                onSelectThreat={setSelectedThreat} 
            />
        </div>
    );
};
